### ISSUE TITLE
Maturity Level % not updating past 2nd "level"

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#1]
When adding more than two levels, updating an input field does not update the % markers.

example: https://data.urbandatacentre.ca/dataset/edit/50th-percentile-rent-estimates

**Comment by bgajdero** [comment]
This missing % updated on the tab labels. The % is updated inside the tab's content.

**Comment by bgajdero** [comment]
You mean the number in "maturity_level_XX" myst be X = 1,2,3,4,etc?

**Comment by LesterLyu** [comment]
> You mean the number in "maturity_level_XX" myst be X = 1,2,3,4,etc?

Yes

**Comment by bgajdero** [comment]
Created a new issue for this
https://github.com/csse-uoft/ckanext-udc/issues/4
