### ISSUE TITLE
Update CUDR logo

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#22]
Replace logo in the top right corner with this one.

![udc_logo](https://user-images.githubusercontent.com/168104/225674000-f64866da-6e31-4f9c-b7d7-1f1e3910dcf3.png)

**Comment by LesterLyu** [comment]
This image is missing the transparency channel, the background is white.

**Comment by bgajdero** [comment]
![UDC_logo_transparent](https://user-images.githubusercontent.com/168104/225961351-c62b34db-95a0-470f-b94a-c5a2465800f5.png)
