### ISSUE TITLE
"Popular Tags" not displaying on index, below Search bar

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#28]
"Popular Tags" is empty. 
Is this a broken feature of CKAN?

It should be displaying tags and their counts, sorted in descending order by count.

<img width="1167" alt="Screenshot 2023-04-04 at 14 42 17" src="https://user-images.githubusercontent.com/168104/229888616-92617cfe-ab5f-48b0-85bc-398c5a123bbd.png">

**Comment by LesterLyu** [comment]
A bug for CKAN: https://github.com/ckan/ckan/issues/7519
