### ISSUE TITLE
When providing a URL as the dataset resource, don't load into visualisation tools

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#35]
Example:
https://data.urbandatacentre.ca/dataset/civil-aviation-fuel-consumption-canadian-air-carriers-levels-i-to-iii-annual/resource/2f40cdee-98f5-410d-ad88-4c5dc9b5465c

Should not load the visualisation unless it is a link to the actual data. Otherwise, the response HTML is parsed and visualized incorrectly.

**Comment by LesterLyu** [comment]
Please remove the view if you don't want to visualize it.

**Comment by bgajdero** [comment]
We need functionality to do this pragmatically.

**Comment by bgajdero** [comment]
Visualization is currently turned off, to save space.
