### ISSUE TITLE
Search results shows "datasets", convert to "Catalogues"

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#56]
Search results displays "datasets", and "dataset" when 1 result is found.

Needs to be converted to "catalogues" and "catalogue"

[Example](https://data.urbandatacentre.ca/dataset/?res_format=CSV%2C+TAB%2C+IVT)

<img width="1230" alt="Screenshot 2023-10-18 at 08 37 43" src="https://github.com/csse-uoft/ckanext-udc/assets/168104/2014d26b-44a1-4b6c-a2a2-a9b025889d3e">

**Comment by LesterLyu** [comment]
Looks like this is imported via Giriraj's import script, which does not give the correct package type and imported into datasets.

**Comment by hgiriraj79** [comment]
I have pushed the above suggested code changes for ckan-import repo. This issue can now be closed.
