### ISSUE TITLE
After bulk upload, change message show link to newly created Cataloge entires and dataset

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#61]
The current message displays labels and text of the newly created catalogue entries and datasets.

The new message displays a table of links to the new entries and datasets:

**3 Catalogue Entries were successfully created**
<table>
<tr><th>Catalogue Entry Name</th><th>Link</th><th>Dataset</th></tr>
<tr><td>My Dataset Name</td><td><a href="a1-my-name-a">a1-my-name-a</a> </td><td><a href="1akdhfe-abcd">1akdhfe-abcd</a></td></tr>
</table>
 
<img width="1049" alt="Screenshot 2023-10-18 at 18 38 58" src="https://github.com/csse-uoft/ckanext-udc/assets/168104/a95a3927-3fa8-49ed-8485-80da88851d0b">

**Comment by LesterLyu** [comment]
![image](https://github.com/csse-uoft/ckanext-udc/assets/7830679/495ddbe5-7758-4c82-8353-c453c8bec4d8)
