### ISSUE TITLE
Fields not being updated

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#63]
**Languages:**
- Languages imported as Polish saved as "file:///Polish" in graph.
- Displays as empty.
- adding from list on screen adds them. removing does not remove.

**License**
- url imported save as url, not formatted or matched to predefined list of licenses in CKAN
- in KS, license still showing "TODO", even though an updated was correctly saved.

**Identifier**
- display showing what was imported, by identifier in KG is a UUID.
- needs to be the value that is saved.

**Data Service**
- updating this field makes the catalogue uneditable.
- see #62

**Comment by LesterLyu** [comment]
"file:///Polish" is something left over from the previous ckan data that does not use the ontology.
This is not visible in the dropdown. (will be removed automatically by https://github.com/csse-uoft/ckanext-udc/commit/18240ffd068d487c2dfc321faf1f872b7e986cdb)
We will need some script to transform the existing data to the new format when we deploy the KG integration.
