### ISSUE TITLE
Dataset page not loading correctly

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#75]
Sometime a dataset page does not load properly. Possibly due to removed data-viewer plugin being removed.

Example: https://data.urbandatacentre.ca/catalogue/residential-property-buyers-first-time-home-buyer-status-and-price-to-income-ratio/resource/5b0b6ae1-0c81-4bf7-8622-1ae84268dc25

Console errors (show up even though page does not show errors):
![Screenshot 2024-01-19 at 13 12 39](https://github.com/csse-uoft/ckanext-udc/assets/168104/91b72dfb-4abd-4f43-a59b-b5874346c682)

Screenshot of invalid page
![Screenshot 2024-01-19 at 13 12 56](https://github.com/csse-uoft/ckanext-udc/assets/168104/4e4ddfd7-5a4a-4e99-9568-bd77feb33a4f)

**Comment by LesterLyu** [comment]
Fixed. Reinstalled solr to limit logs do not occupy the whole disk.
