### ISSUE TITLE
Maturity model config JSON not retained after reboot

### ISSUE THREAD

**Issue by bgajdero** [csse-uoft/ckanext-udc#8]

**Comment by LesterLyu** [comment]
Cannot replicate, Need more information on how it is triggered.

**Comment by bgajdero** [comment]
Same is happening with latest JSON Config object. 
When a new or edit dataset screen is opened, an old version of the JSON object keeps popping up.

**Comment by bgajdero** [comment]
Proposed fix, to force a refresh, add a button beside Config Update to restart the server.
Seems to cause minimal outage
![Screenshot 2023-07-07 at 11 27 32](https://github.com/csse-uoft/ckanext-udc/assets/168104/89237072-19aa-47a2-857a-6a7f528ddf4b)

**Comment by LesterLyu** [comment]
This is possibly fixed already among other bugfixes.
https://github.com/csse-uoft/ckanext-udc/commit/dce09593edaa41d89798727c12fc2012b4e2ef3f : Using [IConfigurable](https://docs.ckan.org/en/2.10/extensions/plugin-interfaces.html?highlight=configure#ckan.plugins.interfaces.IConfigurable.configure) to load UDC Plugin.
